// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ebpfCgCtl struct {
	_         structs.HostLayout
	PeriodNs  uint64
	RuntimeNs uint64
}

type ebpfCgState struct {
	_            structs.HostLayout
	CycleStartNs uint64
	ConsumedNs   uint64
	InRuntime    uint8
	SawSigusr1   uint8
	Pad          [6]uint8
}

type ebpfCpuState struct {
	_        structs.HostLayout
	LastTs   uint64
	LastCgid uint64
}

// loadEbpf returns the embedded CollectionSpec for ebpf.
func loadEbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ebpf: %w", err)
	}

	return spec, err
}

// loadEbpfObjects loads ebpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ebpfObjects
//	*ebpfPrograms
//	*ebpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ebpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfSpecs struct {
	ebpfProgramSpecs
	ebpfMapSpecs
	ebpfVariableSpecs
}

// ebpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfProgramSpecs struct {
	TpSchedSwitch   *ebpf.ProgramSpec `ebpf:"tp_sched_switch"`
	TpSignalDeliver *ebpf.ProgramSpec `ebpf:"tp_signal_deliver"`
}

// ebpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfMapSpecs struct {
	CgCtlMap   *ebpf.MapSpec `ebpf:"cg_ctl_map"`
	CgStateMap *ebpf.MapSpec `ebpf:"cg_state_map"`
	Counters   *ebpf.MapSpec `ebpf:"counters"`
	CpuLast    *ebpf.MapSpec `ebpf:"cpu_last"`
	PidCtlMap  *ebpf.MapSpec `ebpf:"pid_ctl_map"`
}

// ebpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpfVariableSpecs struct {
}

// ebpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfObjects struct {
	ebpfPrograms
	ebpfMaps
	ebpfVariables
}

func (o *ebpfObjects) Close() error {
	return _EbpfClose(
		&o.ebpfPrograms,
		&o.ebpfMaps,
	)
}

// ebpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfMaps struct {
	CgCtlMap   *ebpf.Map `ebpf:"cg_ctl_map"`
	CgStateMap *ebpf.Map `ebpf:"cg_state_map"`
	Counters   *ebpf.Map `ebpf:"counters"`
	CpuLast    *ebpf.Map `ebpf:"cpu_last"`
	PidCtlMap  *ebpf.Map `ebpf:"pid_ctl_map"`
}

func (m *ebpfMaps) Close() error {
	return _EbpfClose(
		m.CgCtlMap,
		m.CgStateMap,
		m.Counters,
		m.CpuLast,
		m.PidCtlMap,
	)
}

// ebpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfVariables struct {
}

// ebpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpfPrograms struct {
	TpSchedSwitch   *ebpf.Program `ebpf:"tp_sched_switch"`
	TpSignalDeliver *ebpf.Program `ebpf:"tp_signal_deliver"`
}

func (p *ebpfPrograms) Close() error {
	return _EbpfClose(
		p.TpSchedSwitch,
		p.TpSignalDeliver,
	)
}

func _EbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ebpf_bpfeb.o
var _EbpfBytes []byte
